[battery]
charging_symbol = "â‡¡ "
discharging_symbol = "â‡£ "
empty_symbol = "â— "
full_symbol = "â€¢ "
unknown_symbol = "â“ "

[cmake]
style = "blue"
symbol = "ğš« "
version_format = "${major}.${minor}"

[directory]
truncation_symbol = "â€¦/"

[git_branch]
symbol = "ğŸ„ "

[nodejs]
symbol = "â¬¡ "
